### ISSUE TITLE
Crashes Mac

### ISSUE THREAD

**Issue by brittanymanuel-cs** [rlane/rlane-oni-mods#3]
Machine: iMac (27-inch, Late 2013)
Version: ONI QOL Mk3
Issue: When mod is enabled game crashes during Klei splash screen. Due to how the mods are set up I am forced to uninstall Steam to get all the files and settings removed in order to have a working game. Your other mod (Alarm) doesn't have this issue for me. I have no logs currently since I had to re-install steam, let me know if there is some way I can help debug this as I would like to use this mod.

**Comment by rlane** [comment]
I pushed a new version to Steam Workshop that might help (includes f3a3ebda). It removes some dependencies on libraries that might not exist on Mac, trimming it to the same set as Alarm. Could you try it and let me know if it works? Unfortunately I don't have a Mac to test with.

Having to reinstall Steam is not great. If the fix above doesn't work and you haven't tried this already, I'd try unsubscribing from the mod and deleting ~/Library/Application Support/unity.Klei.Oxygen Not Included/mods/Steam/1733560461/ (my best guess for where the mod is located on Mac).

**Comment by brittanymanuel-cs** [comment]
Tried this just now, it still crashes, no new symptoms or messages. I did save my Player.logs from the Klei post "Logs and Useful Information for Bug Reports" for my Mac. Here's the pastebin: https://pastebin.com/DYC34zU6. Hopefully it can help you with whatever the issue is. Let me know if there's any other info you need.

The mod is in that directory you listed, I was able to unsub and delete that folder. This does make it so I don't have to re-install steam, so thank you for that fix! 

I'm happy to test whatever mods on my Mac so this can try to be resolved.

**Comment by rlane** [comment]
Pushed a new version with ad82d96 which might help given that the callstack includes GameObject::WillDestroyGameObject(). Harmony had previously been patching unrelated objects.

**Comment by brittanymanuel-cs** [comment]
Still crashed, this time my Mac recognized the crash and gave me a crash report. Here's the info if it is helpful to you. https://pastebin.com/WHQUei13

**Comment by rlane** [comment]
Tried running ONI on Linux with all the mods from https://pastebin.com/DYC34zU6 but couldn't reproduce the crash.

Does the crash occur when only the MeteorDefenseLaser mod is loaded?

**Comment by brittanymanuel-cs** [comment]
Yes, only with the Defense Laser. I've tried doing just the Laser and none other, still crashes, then with all my other mods as well. I can install it with no crashes but as soon as I enable it and restart the game is when it crashes on "Klei" screen, so I can't even disable it I have to do the uninstall and go to the Lib/.../mods/... folder to delete everything.
